name: Test

on:
  push:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: go build -v ./...

      - name: Test
        id: test
        run: |
          json=$(go test ./... -json)
          status=$?
          [ $status -eq 0 ] && echo "command was successful" || echo "failed"
          echo $json
          echo "::set-output name=test2json::$json"

      - name: Summary
        if: always()
        run: |
          echo "${{ steps.test.outputs.test2json }}" | go run ./test_parser.go >> $GITHUB_STEP_SUMMARY
          echo $GITHUB_STEP_SUMMARY
