name: Test

on:
  push:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: go build -v ./...

      - name: Test
        id: test
        run: |
          status=0
          json=$(go test ./... -json) || status=1
          
          echo 'TEST2JSON<<EOF' >> $GITHUB_ENV
          echo "$json" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
          
          [ $status -eq 0 ] && echo "passed" || echo "failed" ; exit 1

      - name: Summary
        if: always()
        run: |
          echo "${{ env.TEST2JSON }}" | go run ./test_parser.go >> $GITHUB_STEP_SUMMARY
          echo $GITHUB_STEP_SUMMARY
