name: Test

on:
  push:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: go build -v ./...

      - name: Test
        id: test
        run: |
          JSON_OUTPUT="$(go test ./... -json)"
          echo "::set-output name=output::${JSON_OUTPUT}"

      - name: Summary
        run: |
          go run ./test_parser.go ${{ steps.test.outputs.output }} >> $GITHUB_STEP_SUMMARY
          echo $GITHUB_STEP_SUMMARY
