name: Test

on:
  push:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: go build -v ./...

      - name: Test
        id: test
        run: |
          echo "before test"
          status=0
          json=$(go test ./... -json) || status=1
          echo "::set-output name=test2json::$json"
          [ $status -eq 0 ] && echo "passed" || echo "failed" ; exit 1

      - name: Summary
        if: always()
        run: |
          printf '%s\n' "${{ steps.test.outputs.test2json }}" | go run ./test_parser.go >> $GITHUB_STEP_SUMMARY
          echo $GITHUB_STEP_SUMMARY
